package com.example.model

import androidx.compose.ui.graphics.Color

enum class GameTheme(
    val title: String,
    val isDark: Boolean,
    val backgroundColor: Color,
    val surfaceColor: Color,
    val boardBackground: Color,
    val gridDotColor: Color,
    val arrowPrimaryColor: Color,
    val arrowSecondaryColor: Color,
    val arrowHighlightColor: Color,
    val arrowBlockedColor: Color,
    val textPrimaryColor: Color,
    val textSecondaryColor: Color,
    val accentColor: Color
) {
    CLASSIC(
        title = "Sunny Yellow",
        isDark = false,
        backgroundColor = Color(0xFFFFFBEB),
        surfaceColor = Color(0xFFFFFFFF),
        boardBackground = Color(0xFFFDE047),
        gridDotColor = Color(0xFFD97706),
        arrowPrimaryColor = Color(0xFF1D4ED8),
        arrowSecondaryColor = Color(0xFF7E22CE),
        arrowHighlightColor = Color(0xFF0284C7),
        arrowBlockedColor = Color(0xFFEF4444),
        textPrimaryColor = Color(0xFF78350F),
        textSecondaryColor = Color(0xFF92400E),
        accentColor = Color(0xFFF59E0B)
    ),
    MIDNIGHT(
        title = "Midnight",
        isDark = true,
        backgroundColor = Color(0xFF090D16),
        surfaceColor = Color(0xFF111827),
        boardBackground = Color(0xFF0F172A),
        gridDotColor = Color(0xFF334155),
        arrowPrimaryColor = Color(0xFF38BDF8),
        arrowSecondaryColor = Color(0xFF60A5FA),
        arrowHighlightColor = Color(0xFFF472B6),
        arrowBlockedColor = Color(0xFFF87171),
        textPrimaryColor = Color(0xFFF8FAFC),
        textSecondaryColor = Color(0xFF94A3B8),
        accentColor = Color(0xFF38BDF8)
    ),
    OCEAN(
        title = "Ocean Wave",
        isDark = true,
        backgroundColor = Color(0xFF041C2C),
        surfaceColor = Color(0xFF082F49),
        boardBackground = Color(0xFF07263D),
        gridDotColor = Color(0xFF164E63),
        arrowPrimaryColor = Color(0xFF22D3EE),
        arrowSecondaryColor = Color(0xFF06B6D4),
        arrowHighlightColor = Color(0xFF34D399),
        arrowBlockedColor = Color(0xFFFB7185),
        textPrimaryColor = Color(0xFFE0F2FE),
        textSecondaryColor = Color(0xFF7DD3FC),
        accentColor = Color(0xFF06B6D4)
    ),
    SUNSET(
        title = "Sunset Amber",
        isDark = true,
        backgroundColor = Color(0xFF1A0B2E),
        surfaceColor = Color(0xFF26123D),
        boardBackground = Color(0xFF200E34),
        gridDotColor = Color(0xFF4C1D95),
        arrowPrimaryColor = Color(0xFFFB923C),
        arrowSecondaryColor = Color(0xFFF43F5E),
        arrowHighlightColor = Color(0xFFFACC15),
        arrowBlockedColor = Color(0xFFDC2626),
        textPrimaryColor = Color(0xFFFDF4FF),
        textSecondaryColor = Color(0xFFC084FC),
        accentColor = Color(0xFFFB923C)
    ),
    CARAMEL(
        title = "Caramel Pup",
        isDark = false,
        backgroundColor = Color(0xFFFFFBEB),
        surfaceColor = Color(0xFFFEF3C7),
        boardBackground = Color(0xFFFDE68A),
        gridDotColor = Color(0xFFD97706),
        arrowPrimaryColor = Color(0xFFD97706),
        arrowSecondaryColor = Color(0xFFB45309),
        arrowHighlightColor = Color(0xFFF59E0B),
        arrowBlockedColor = Color(0xFFEF4444),
        textPrimaryColor = Color(0xFF78350F),
        textSecondaryColor = Color(0xFF92400E),
        accentColor = Color(0xFFF59E0B)
    ),
    FOREST(
        title = "Enchanted Forest",
        isDark = false,
        backgroundColor = Color(0xFFF0FDF4),
        surfaceColor = Color(0xFFDCFCE7),
        boardBackground = Color(0xFFA7F3D0),
        gridDotColor = Color(0xFF059669),
        arrowPrimaryColor = Color(0xFF059669),
        arrowSecondaryColor = Color(0xFF047857),
        arrowHighlightColor = Color(0xFF34D399),
        arrowBlockedColor = Color(0xFFF43F5E),
        textPrimaryColor = Color(0xFF064E3B),
        textSecondaryColor = Color(0xFF065F46),
        accentColor = Color(0xFF10B981)
    ),
    CANDY_PINK(
        title = "Sweet Bunny",
        isDark = false,
        backgroundColor = Color(0xFFFDF2F8),
        surfaceColor = Color(0xFFFCE7F3),
        boardBackground = Color(0xFFFBCFE8),
        gridDotColor = Color(0xFFDB2777),
        arrowPrimaryColor = Color(0xFFEC4899),
        arrowSecondaryColor = Color(0xFFDB2777),
        arrowHighlightColor = Color(0xFFF472B6),
        arrowBlockedColor = Color(0xFFEF4444),
        textPrimaryColor = Color(0xFF831843),
        textSecondaryColor = Color(0xFF9D174D),
        accentColor = Color(0xFFEC4899)
    )
}
